version: "3.5"

services:
  init:
    image: busybox:latest
    entrypoint: ["/bin/sh", "-c"]
    command: |
      - "chown -R 1000:1000 /kafka;"
    volumes:
      - ./mm2.properties:/kafka/
    restart: 'no'

  mmv2:
    image: kafka-mm2:3.5
    volumes:
      - ./mm2.properties:/opt/kafka/config/mm2.properties
    environment:
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
    restart: always
